version: "3"
services:
  web:
    build: .
    container_name: camagru_app
    ports:
      - "80:80"
    volumes:
     - ./app/:/var/www/html/
    links:
     - db
     - mail
  db:
    image: mysql:5.7
    container_name: camagru_db
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
     - "volume:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: camagru_phpmyadmin
    ports:
      - "8081:80"
    links:
      - db
  mail:
    image: namshi/smtp
    container_name: camagru_smtp
    ports:
      - "25:25"
    environment:
      GMAIL_USER: $GMAIL_USER
      GMAIL_PASSWORD: $GMAIL_PASSWORD
volumes:
  volume: