version: "3"
services:
  web:
    build: .
    container_name: camagru_app
    ports:
      - "80:80"
    volumes:
     - ./app/:/var/www/html/
  db:
    image: mysql:5.7
    container_name: camagru_db
    environment:
     - MYSQL_ROOT_PASSWORD=mpressen
     - MYSQL_DATABASE=camagru_db
    volumes:
     - "volume:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: camagru_phpmyadmin
    ports:
      - "8081:80"
volumes:
  volume: